In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
NBA_stats_renamed_df = pd.read_csv("FINAL_NBA_Stats.csv")
NCAA_stats_renamed_df = pd.read_csv("FINAL_NCAA_Stats.csv")

In [3]:
NBA_stats_renamed_df

,G,MP,2P,2PA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,82,2605,519,1206,119,296,214,255,57,179,236,243,44,6,185,186,1371
1,9,133,15,22,0,0,9,18,14,24,38,4,3,6,5,23,39
2,68,931,141,360,45,130,34,43,14,38,52,117,21,3,63,95,361
3,73,1687,225,600,63,205,80,102,58,248,306,118,55,12,114,178,593
4,29,615,63,138,4,14,37,52,39,115,154,43,39,16,26,61,167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,63,1266,158,300,1,10,32,47,101,211,312,44,54,23,41,124,349
415,36,232,35,84,9,29,10,21,6,26,32,18,6,9,8,17,89
416,1,2,1,1,0,0,0,0,0,1,1,0,0,0,0,1,2
417,2,17,3,9,0,4,0,0,0,3,3,2,0,0,0,0,6
418,10,109,12,32,7,19,4,5,5,12,17,4,4,2,4,9,35

In [4]:
NCAA_stats_renamed_df

,G,MP,2P,2PA,3P,3PA,FT,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,33,29.9,4.6,9.3,1.3,4.0,5.9,7.6,1.0,2.7,3.8,3.6,0.8,0.1,2.8,2.5,19.2
1,34,26.8,3.9,6.3,0.0,0.0,2.6,3.6,2.7,6.1,8.8,0.5,0.5,1.6,1.1,1.8,10.5
2,31,25.5,2.4,5.8,1.0,3.8,1.0,1.5,1.5,4.2,5.8,0.6,0.6,0.5,1.4,1.7,8.8
3,38,28.4,3.4,7.2,1.1,3.1,3.5,4.7,2.0,4.5,6.5,1.7,1.5,0.4,2.2,2.6,13.8
4,38,28.7,3.5,6.5,0.2,0.8,3.8,5.4,2.0,4.8,6.8,1.6,1.2,0.8,1.6,2.5,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,31,34.9,5.5,10.3,0.5,1.4,3.7,4.7,1.4,5.8,7.2,2.5,1.2,1.2,2.3,2.2,16.1
415,32,38.2,5.6,12.1,1.6,5.3,6.3,8.4,1.0,7.5,8.5,4.4,1.5,0.6,4.2,2.1,22.1
416,21,33.1,4.2,8.0,0.6,2.1,4.8,6.5,0.5,3.8,4.3,5.0,1.3,0.8,2.8,2.4,15.0
417,34,29.7,2.9,5.1,1.4,3.8,2.8,3.4,1.3,3.1,4.5,2.9,1.4,0.4,2.0,2.2,12.9
418,29,31.0,3.8,7.9,1.9,5.2,3.7,4.7,0.7,5.6,6.3,3.6,0.9,1.3,2.6,2.7,17.1

In [5]:
from sklearn.model_selection import train_test_split
variables = NCAA_stats_renamed_df.columns
for line in variables:
    print(line)
    X = NCAA_stats_renamed_df[line].values.reshape(-1, 1)
    y = NBA_stats_renamed_df[line].values.reshape(-1, 1)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    
    # Linear Regression
    reg = LinearRegression().fit(X_train, y_train)
    score = reg.score(X_train, y_train)
    print(f"Linear Regression Score: {score}")
    #prediction = reg.predict(np.array([[3, 5]]))
    
    # Random Forest
    regr = RandomForestRegressor(max_depth=2, random_state=0)
    regr.fit(X_train, y_train)

    training_score = regr.score(X_train, y_train)
    testing_score = regr.score(X_test, y_test)
    print(f"Random Forest Score: {training_score}")
    #print(f"Testing Score: {testing_score}")

#     plt.scatter(X_train, y_train,  color='black')
#     plt.title("Training Data")
#     plt.xlabel(f"NCAA {line}")
#     plt.ylabel(f"NBA {line}")
#     plt.show()

    print("--------------------")

G
Linear Regression Score: 0.01405937857763162
Random Forest Score: 0.04308057535633303
--------------------
MP
Linear Regression Score: 0.00444654886945095

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.06010149507248275
--------------------
2P
Linear Regression Score: 0.03966714855212472
Random Forest Score: 0.1385025338933661
--------------------
2PA

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Linear Regression Score: 0.028030141209356985
Random Forest Score: 0.07432220946043067
--------------------
3P
Linear Regression Score: 0.14603723202976449
Random Forest Score: 0.22565357865512925
--------------------
3PA
Linear Regression Score: 0.13035930423895525

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.1981793653221522
--------------------
FT
Linear Regression Score: 0.043559358573605045
Random Forest Score: 0.17289972561655753

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

--------------------
FTA
Linear Regression Score: 0.04075744772176315

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.1271039080431685
--------------------
ORB
Linear Regression Score: 0.0829296115330116
Random Forest Score: 0.1769966829654711
--------------------
DRB

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Linear Regression Score: 0.01834244065178703
Random Forest Score: 0.0845397222645401
--------------------
TRB

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Linear Regression Score: 0.02917398504954105

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.10913744724205476
--------------------
AST
Linear Regression Score: 0.15831304333039664

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.36905779290575413
--------------------
STL
Linear Regression Score: 0.05950229619339309

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.12008688511850041
--------------------
BLK
Linear Regression Score: 0.12203500517744792

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.16683356690535367
--------------------
TOV
Linear Regression Score: 0.0922963862150743

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.24042697557325354
--------------------
PF
Linear Regression Score: 0.025930849873551542

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.07293058420736442
--------------------
PTS
Linear Regression Score: 0.052907678329366825

C:\Users\Admin\anaconda3\envs\PythonAdv\lib\site-packages\ipykernel_launcher.py:18: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Random Forest Score: 0.17423760008586275
--------------------